server:
  port: 9191
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        default_schema: microservices
        show_sql: true
        format_sql: true
        ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/r4db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    name: microservices
